### PR TITLE
proposal to rename long path to something less tragic

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 Do not merge. I just want to show what need to be changed in order to rename the file

**Comment by Yuri05** [comment]
fine with that. could rename

**Comment by msevestre** [comment]
All right then

Probably for 7.4 we could rename all those files again to not duplicate project name in simulation name.
The first simulation could be called default, and other have the extra name that they have already

**Comment by Yuri05** [comment]
>Probably for 7.4 we could rename all those files again to not duplicate project name in simulation name.
The first simulation could be called default, and other have the extra name that they have already

Yep, would be good

**Pull request merged**
